apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubecost-ui
  namespace: kubecost
spec:
  ingressClassName: nginx
  rules:
  - host: domain.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubecost-cost-analyzer
            port:
              number: 9090