prometheus:
  server:
    global:
      external_labels:
        cluster_id: jesse-aks1
kubecostProductConfigs:
  clusterName: dev_clusters
  productKey:
    secretname: productkey
    enabled: true
  cloudIntegrationSecret: cloud-integration # only runs on primary cluster
  azureBillingRegion: US
  serviceKeySecretName: azure-service-key